---
title: "Final_Assignment"
author: "Leon Edmiidz, Zach Ribau"
date: "2024-02-20"
output: pdf_document
---

## HEADER

```{r}

##----------------------
### Load Libraries & Data
##-----------------------

#Define function to install libraries if not already installed on system
install_if_needed <- function(package_name) {
  if (!require(package_name, character.only = TRUE)) {
    install.packages(package_name)
    library(package_name, character.only = TRUE)
  }
}

#Create vector with required libraries
packages <- c("tidyverse","glmnet", "ggplot2","lars", "caret", "ggplot2", "GGally")

#Loop over package vector and install and load libraries
for (pkg in packages) {
  install_if_needed(pkg)
}

#load in diabetes dataset
data("diabetes")
attach(diabetes)

#Combine matrices to visualize as dataframe include row ID
full_dataset = data.frame(cbind(diabetes$x, diabetes$x2, y = diabetes$y))


##----------------------
### Data Splitting
##----------------------

#Combine X and X2 matrices, as we will train a model with all available  features.

x_combined <- cbind(x, x2)

#Set seed for reproducibility
set.seed(1545)

#Hold out 42 observations for testing
test_set_size <- 42 
test.index <- sample.int(dim(x_combined)[1], test_set_size, replace = FALSE)

#Check for standardization, even though glmnet inherently standardizes
plot(as.ts(apply(x_combined, 2, sd)), xlab="Covariate", ylab="Standard Deviation") 

#Subset training data
x_training <- x_combined[-test.index, ]
y_training <- y[-test.index]

#Subset the testing data
x_testing <- x_combined[test.index, ]
y_testing <- y[test.index]

```

```{r}

##----------------------
### Cross Validation
##----------------------

lasso1 <- cv.glmnet(x_training, y_training, type.measure="mse", nfolds=10)
plot(lasso1) 

lasso1$lambda.min
lasso1$lambda.1se


##----------------------
### Testing 
##----------------------

#Predict response variable in testing data using lambda min and lamnbda 1se
prd_all <- predict(lasso1, newx=x_testing, s=c(lasso1$lambda.min, lasso1$lambda.1se))

#Compute and print MSE for both models
(mse_lambda_min <- mean((y_testing - prd_all[,1])^2))
(mse_lambda_1se <- mean((y_testing - prd_all[,2])^2))




```
